simpleArgs: &simple-args
  initialMoney: 10000
  moneyToTransfer: 100
  numberOfAccounts: &number-of-accounts 1000

test:
  name: simple-open
  description: Rodada de Open (Abertura de Contas) - Besu
  workers:
    number: 5
  rounds:
    - label: open
      description: Teste de abertura de contas no Besu.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: caliper_besu/facicoin_write1.js
        arguments: *simple-args
