simpleArgs: &simple-args
  initialMoney: 200
  moneyToTransfer: 100
  numberOfAccounts: &number-of-accounts 20

test:
  name: facicoin-mint-benchmark
  description: Teste de carga da funcao mintReward
  workers:
    number: 5
  rounds:
    - label: mintReward
      description: Executando mintReward
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: caliper_besu/mintReward.js
        arguments: *simple-args
