simpleArgs: &simple-args
  initialMoney: 10000
  moneyToTransfer: 100
  numberOfAccounts: &number-of-accounts 1000

test:
  name: facicoin-marketplace-benchmark
  description: Teste de carga da funcao createMentorship
  workers:
    number: 5
  rounds:
    - label: createMentorship
      description: Executando createMentorship
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: caliper_besu/createMentorship.js
        arguments:
          << : *simple-args
          money: 100
